### ISSUE TITLE
Support Processing 3

### ISSUE THREAD

**Issue by tibfox** [davidbouchard/keystone#1]
When I execute the example sketch within Processing 3, I get the following error:

java.lang.RuntimeException: java.lang.NoClassDefFoundError: processing/core/PGraphicsJava2D
    at processing.opengl.PSurfaceJOGL$2.run(PSurfaceJOGL.java:451)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: processing/core/PGraphicsJava2D
    at deadpixel.keystone.Keystone.<init>(Unknown Source)
    at CornerPin.setup(CornerPin.java:50)
    at processing.core.PApplet.handleDraw(PApplet.java:2378)
    at processing.opengl.PSurfaceJOGL$DrawListener.display(PSurfaceJOGL.java:861)
    at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:692)
    at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:674)
    at jogamp.opengl.GLAutoDrawableBase$2.run(GLAutoDrawableBase.java:443)
    at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1293)
    at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
    at com.jogamp.newt.opengl.GLWindow.display(GLWindow.java:759)
    at com.jogamp.opengl.util.AWTAnimatorImpl.display(AWTAnimatorImpl.java:81)
    at com.jogamp.opengl.util.AnimatorBase.display(AnimatorBase.java:452)
    at com.jogamp.opengl.util.FPSAnimator$MainTask.run(FPSAnimator.java:178)
    at java.util.TimerThread.mainLoop(Timer.java:555)
    at java.util.TimerThread.run(Timer.java:505)
Caused by: java.lang.ClassNotFoundException: processing.core.PGraphicsJava2D
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 15 more

**Comment by davidbouchard** [comment]
Keystone works fine on Processing 3 (as of 3.1.1). Tested on Mac, Windows and Linux. Make sure you run the latest version of the library.

**Comment by tibfox** [comment]
Oh yeah. That was the problem. Installation was successful after some weird installation steps ^^
1. Install it from library manager in processing
2. download the version of here and paste it over the existing library content in my library path

just downloading this here and install it like other libraries just would not work for me. hah

thanks
